language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.0

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

defaults: &defaults
  install:
  - travis_wait 20 yarn install
  before_script:
  # Run application
  - yarn run cypress open
  ## print all Travis environment variables for debugging
  #- npm start -- --silent &
  #- npm run cy:run -- --record --parallel --group $STAGE_NAME
  script:
  #    - $(npm bin)/print-env TRAVIS
  - node_modules\.bin\cypress run --record --key 9942e243-4a25-4765-8e72-62aa318a561e

  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  - kill $(jobs -p) || true